services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus:/prometheus
     
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml' 
        
  mailserver:
    image: jijiechen/papercut:latest
    container_name: ddd.papercut
    ports: # exposes port 25 internally
      - 37409:37408
  
  api:
    image: api
    ports:
      - "8181:8080"
    build:
      context: .
      dockerfile: Api/Dockerfile
      
volumes:
  prometheus:
    driver: local
