global: 
  scrape_interval: 10s
  scrape_timeout: 5s
rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'prometheus:9093'
scrape_configs:
  - job_name: "api"
    static_configs: 
      - targets: ["api:8080"]